apply(['plugin': 'com.android.application'])
android { 
    ndkVersion('23.2.0')
    compileSdkVersion(33)
    buildToolsVersion('33.0.0')
    defaultConfig { 
        externalNativeBuild { 
            ndk { 
                abiFilters('riscv64')
            }
        }
        applicationId "com.emanuelef.remote_capture"
        minSdkVersion(29)
        targetSdkVersion(33)
        versionCode(71)
        versionName('1.6.8')
        buildConfigField('long', 'BUILD_TIME', java.lang.System.currentTimeMillis() + 'L')
    }
    buildTypes { 
        release { 
            minifyEnabled(false)
        }
        debug { 
            applicationIdSuffix('.debug')
            versionNameSuffix('-beta')
            pseudoLocalesEnabled(true)
            if (project.hasProperty('doNotStrip')) {
                packagingOptions { 
                    doNotStrip('**/libpcapd.so')
                    doNotStrip('**/libcapture.so')
                }
            }
        }
    }
    packagingOptions { 
        jniLibs { 
            useLegacyPackaging = true
        }
    }
    externalNativeBuild { 
        cmake { 
            path(file('src/main/jni/CMakeLists.txt'))
            version('3.22.1')
        }
    }
    compileOptions { 
        encoding('UTF-8')
        sourceCompatibility(JavaVersion.VERSION_1_8)
        targetCompatibility(JavaVersion.VERSION_1_8)
    }
    sourceSets { 
        main.java.srcDirs += '../submodules/MaxMind-DB-Reader-java/src/main/java'
    }
    testOptions { 
        unitTests.includeAndroidResources = true
    }
    namespace('com.emanuelef.remote_capture')
}
dependencies { 
    testImplementation('junit:junit:4.13.2')
    testImplementation('androidx.test:core:1.5.0')
    testImplementation('org.robolectric:robolectric:4.10.3')
    implementation('androidx.appcompat:appcompat:1.6.1')
    implementation('androidx.constraintlayout:constraintlayout:2.1.4')
    implementation('androidx.fragment:fragment:1.5.7')
    implementation('androidx.localbroadcastmanager:localbroadcastmanager:1.1.0')
    implementation('androidx.preference:preference:1.2.0')
    implementation('androidx.recyclerview:recyclerview:1.3.0')
    implementation('androidx.navigation:navigation-fragment:2.5.3')
    implementation('androidx.navigation:navigation-ui:2.5.3')
    implementation('com.google.android.material:material:1.9.0')
    implementation('com.google.code.gson:gson:2.9.0')
    implementation('org.brotli:dec:0.1.2')
    implementation('cat.ereza:customactivityoncrash:2.3.0')
    implementation('com.github.KaKaVip:Android-Flag-Kit:v0.1')
    implementation('com.github.AppIntro:AppIntro:6.2.0')
    implementation('com.github.androidmads:QRGenerator:1.0.1')
}
